name: Deploy DocC

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-12
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - name: Build All DocC 🛠
        run: |
          swift package resolve;
          xcodebuild docbuild -scheme DXProtocol -derivedDataPath /tmp/docbuild -destination 'generic/platform=iOS';
          $(xcrun --find docc) process-archive \
            transform-for-static-hosting /tmp/docbuild/Build/Products/Debug-iphoneos/DXProtocol.doccarchive \
            --output-path docs \
            --hosting-base-path DXProtocol;
          echo "<script>window.location.href += \"/documentation/dxprotocol\"</script>" > docs/index.html;

          $(xcrun --find docc) process-archive \
            transform-for-static-hosting /tmp/docbuild/Build/Products/Debug-iphoneos/SwiftProtobuf.doccarchive \
            --hosting-base-path DXProtocol/SwiftProtobuf \
            --output-path docs/SwiftProtobuf

      - name: Upload artifact 📜
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload docs directory
          path: 'docs'
      - name: Deploy to GitHub Pages 🐙
        id: deployment
        uses: actions/deploy-pages@v1
