name: Test Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Get Sources
        uses: actions/checkout@v3
        
      - name: Setup Swift
        uses: swift-actions/setup-swift@v1
        with:
              swift-version: "5.8.0"

      - name: Run tests
        run: swift test --enable-code-coverage
