name: Test all  platforms

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  SCHEME: DXProtocol
  TEST_DEVICE: platform=iOS Simulator,name=iPhone 14,OS=16.2

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
    - name: Checkout project repo
      uses: actions/checkout@v4

    - name: Build
      shell: bash
      run: xcodebuild -scheme '${{ env.SCHEME }}' -sdk iphonesimulator -destination '${{ env.TEST_DEVICE }}' build

  test:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
    - name: Checkout project repo
      uses: actions/checkout@v4

    - name: Test
      shell: bash
      run: xcodebuild -scheme '${{ env.SCHEME }}' -sdk iphonesimulator -destination '${{ env.TEST_DEVICE }}' test
