name: Test Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Get Sources
        uses: actions/checkout@v2
        
      - name: Setup Swift
        uses: swift-actions/setup-swift@v1.24.0
        with:
              swift-version: "5.8.0"
    
      - name: Build Package
        run: swift build -v

      - name: Run tests
        run: swift test --enable-code-coverage -v
      
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.5.1
        with:
          xcode-version: latest

      - name: Gather code coverage
        run: xcrun llvm-cov export -format="lcov" .build/debug/DXProtocolPackageTests.xctest/Contents/MacOS/DXProtocolPackageTests -instr-profile .build/debug/codecov/default.profdata > coverage_report.lcov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: ./coverage_report.lcov
          verbose: true
