name: Test Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Get Sources
        uses: actions/checkout@v2
        
      - name: Setup Swift
        uses: swift-actions/setup-swift@v1.24.0
        with:
              swift-version: "5.8.0"
    
      - name: Build Package
        run: swift build -v

      - name: Run tests
        run: swift test --enable-code-coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./.build/debug/codecov/DXProtocol.json
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
